config/routes.rb
Cmdb::Application.routes.draw do

  resources :pruebas

  get "dashboard/", to: "dashboard#index"
  
  get 'servidores/actualizar_plataforma' => 'servidores#actualizar_plataforma'
  
  resources :servidores do
    
    resources :almacenamientos
    
    resources :contactos
    
  end
  
  resources :usuarios
  
  resources :aplicaciones
  
  resources :base_datos
  
  get "/login", to: "sesiones#new"
  
  post "/login", to: "sesiones#create"
  
  delete "/login", to: "sesiones#destroy"
  
  
  resources :familias
  
  resources :entornos
  
  resources :idiomas
  
  resources :tipo_ups
  
  resources :tipo_licencias
  
  resources :plataformas
  
  resources :ubicaciones
  
  resources :rol_servidores
  
  resources :criticidades
  
  
  resources :areas
  
  resources :arquitecturas
  
  resources :lenguajes
  
  resources :accesos
  
  resources :suministros
  
  resources :estado_aplicaciones
  
  resources :tipo_aplicaciones
  
  resources :seguridad_aplicaciones
  
  resources :mantenimientos
  
  resources :plataforma_bds
  
  resources :tipo_bds
  
  root 'dashboard#index'
  

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(usuario)
    if usuario.rol? :administrador
      can :manage, :all
    end
    
    if usuario.rol? :sistemas
      can :manage, Servidor
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/acceso.rb
class Acceso < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/aplicacion.rb
class Aplicacion < ActiveRecord::Base
paginates_per 10
  validates :nombre, presence: true

  scope :activo, -> { where(activo: 1) }

  belongs_to :area
  belongs_to :arquitectura
  belongs_to :lenguaje
  belongs_to :acceso
  belongs_to :suministro
  belongs_to :estado_aplicacion
  belongs_to :tipo_aplicacion
  belongs_to :seguridad_aplicacion
  belongs_to :mantenimiento
  belongs_to :criticidad
end

app/models/area.rb
class Area < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/arquitectura.rb
class Arquitectura < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/base_dato.rb
class BaseDato < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }

  belongs_to :area
  belongs_to :estado_aplicacion
  belongs_to :plataforma_bd
  belongs_to :tipo_bd
  belongs_to :seguridad_aplicacion
  belongs_to :criticidad
  belongs_to :suministro
  belongs_to :mantenimiento
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }

end

app/models/criticidad.rb
class Criticidad < ActiveRecord::Base
  paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/entorno.rb
class Entorno < ActiveRecord::Base
  paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/familia.rb
class Familia < ActiveRecord::Base
  paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
  paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/lenguaje.rb
class Lenguaje < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/mantenimiento.rb
class Mantenimiento < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/plataforma.rb
class Plataforma < ActiveRecord::Base
 paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/rol_servidor.rb
class RolServidor < ActiveRecord::Base
 paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/servidor.rb
class Servidor < ActiveRecord::Base
has_many :almacenamientos

  paginates_per 10

  belongs_to :tipo_up
  belongs_to :plataforma
  belongs_to :familia
  belongs_to :idioma
  belongs_to :tipo_licencia
  belongs_to :entorno
  belongs_to :criticidad
  belongs_to :rol_servidor
  belongs_to :ubicacion
  
  validates :descripcion, presence: true

  scope :activo, -> { where(activo: 1) }

end

app/models/suministro.rb
class Suministro < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/tipo_bd.rb
class TipoBd < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/tipo_up.rb
class TipoUp < ActiveRecord::Base
  paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
paginates_per 10
  validates :denominacion, presence: true

  scope :activo, -> { where(activo: 1) }
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_secure_password

  paginates_per 10
  validates :nombre, presence: true
  validates :apellidos, presence: true
  validates :correo, presence: true
  validates :usuario, presence: true
  validates :correo, uniqueness: true
  validates :usuario, uniqueness: true

  scope :activo, -> { where(activo: 1) }
  
  scope :con_rol, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0 "} }  

  ROLES = %w[administrador sistemas backup]

  def rol_symbols  
    roles.map(&:to_sym)  
  end  
  
  def roles=(roles)  
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum  
  end  
  
  def roles  
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }  
  end
  
  def rol?(rol)  
    roles.include? rol.to_s  
  end  
end

app/controllers/entornos_controller.rb
class EntornosController < ApplicationController
  before_action :requiere_autenticacion!  
  before_filter :set_entorno, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:create]

  def index
    @entornos = Entorno.activo.page params[:page]
  end
  
  def new
    @entorno = Entorno.new
  end
  
  def edit
  end
  
  def create
    @entorno = Entorno.new(entorno_params)
    if @entorno.save
      flash[:notice] = "Entorno añadido correctamente"
      redirect_to entornos_path
    else
      flash[:alert] = "Hubo un error al añadir el Entorno"
      render "new"
    end
  end

  def update
    if @entorno.update(entorno_params)
      flash[:notice] = "Entorno modificado correctamente"
      redirect_to entornos_path
    else
      flash[:alert] = "Hubo un error al añadir el Entorno"
      render "edit"
    end
  end
  
  def destroy
    @entorno.activo = 0
    @entorno.save
    flash[:notice] = "Entorno borrado correctamente"
    redirect_to entornos_path
  end
  
  private
  def entorno_params
    params.require(:entorno).permit(:denominacion)
  end
  
  def set_entorno
    @entorno = Entorno.activo.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Vaya, parece que ha habido un error al buscar ese Entorno"
    redirect_to entornos_path
  end
end

app/views/entornos/_boton_atras.html.erb
<ul class="minitiles">
  <li class="blue">
    <%= link_to entornos_path, :id => "Atrás" do %>
      <i class="icon-reply"></i>
    <% end %>
  </li>
</ul>

app/views/entornos/_boton_nuevo.html.erb
<ul class="minitiles">
  <li class="blue">
    <%= link_to new_entorno_path, :id => "Nuevo Entorno" do %>
      <i class="glyphicon-circle_plus"></i>
    <% end %>
  </li>
</ul>

app/views/entornos/_cabecera.html.erb
<div class="page-header">
  <div class="pull-left">
    <h1>Entornos</h1>
  </div>  
  <div class="pull-right">
    <div class="pull-right">
      <%=  render 'boton_nuevo' %>
      <%=  render 'layouts/fecha' %>
    </div>
  </div>
</div>

app/views/entornos/_cabecera_formulario.html.erb
<div class="page-header">
  <div class="pull-left">
    <h1>Entornos</h1>
  </div>  
  <div class="pull-right">
    <div class="pull-right">
      <%=  render 'boton_atras' %>
      <%=  render 'layouts/fecha' %>
    </div>
  </div>
</div>

app/views/entornos/_entornos.html.erb
<div class="span12">
  <div class="box box-color box-bordered">
    <div class="box-title">
      <h3>
        <i class="icon-table"></i>
        Entornos
      </h3>
    </div>
    <div class="box-content nopadding">
      <table class="table table-hover table-nomargin">
        <thead>
          <tr>
            <th width="10%">#</th>
            <th>Denominación</th>
            <th width="11%">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @entornos.each do |e| %>
            <tr>
              <td width="10%"><%= e.id %></td>
              <td><%= e.denominacion %></td>
              <td width="11%">
                <%= link_to edit_entorno_path(e), id: "Editar" do %> 
                  <button class="btn btn-warning"><i class="glyphicon-circle_question_mark"></i></button>
                <% end %>
                <%= link_to entorno_path(e), method: :delete, data: { confirm: "¿Seguro que quieres borrar este Entorno?"}, id: "Borrar" do %>
                  <button class="btn btn-danger"><i class="glyphicon-circle_remove"></i></button>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @entornos %>
    </div>
  </div>
</div>

app/views/entornos/_errores.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %>
    <% if @entorno.errors.any? %>
      <div id="error_explanation">
        <%= pluralize(@entorno.errors.count, "error") %>
          debe corregirse:
        <ul>
          <% @entorno.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

app/views/entornos/_form.html.erb
<%= form_for(@entorno) do |f| %>
  <div class="form-group">
    <%= f.label :denominacion, "Denominación", class: "control-label" %>
    <%= f.text_field :denominacion, class: "form-control", placeholder: "Introduce el nombre del Entorno" %>     
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/entornos/edit.html.erb
<%= render "cabecera_formulario" %>
<%= render "layouts/mensajes" %>
<%= render 'errores' %>
<div class="row">   
  <div class="col-md-12">
    <div class="box">
      <div class="box-title">
        <h3><i class="icon-edit"></i>Editar Entorno</h3>
      </div>
      <div class="box-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/entornos/index.html.erb
<%= render "cabecera" %>
<%= render "layouts/mensajes" %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %>
  </div>
<% end %><div class="row">
  <div class="span12">
    <div class="box">
      <div class="box-title">
        <h3>
          <i class="icon-reorder"></i>
          Entornos
        </h3>
      </div>
      <div class="box-content">
        <%= render 'entornos' %>
      </div>
    </div>
  </div>
</div>

app/views/entornos/new.html.erb
<%= render "cabecera_formulario" %>
<%= render "layouts/mensajes" %>
<%= render 'errores' %>
<div class="row">   
  <div class="col-md-12">
    <div class="box">
      <div class="box-title">
        <h3><i class="icon-edit"></i>Añadir Entorno</h3>
      </div>
      <div class="box-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>